In [1]:
import numpy as np

In [4]:
#Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1)
array_2D = np.random.randint(1, 20, (6, 6))
sub_array_2x2 = array_2D[1:3, 1:3]
print(sub_array_2x2)

[[19 13]
 [10  2]]


In [5]:
# 2. From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.
array_3D = np.random.randint(1, 20, (3, 2, 1))
extracted_elements = array_3D[:2, :, 0]
print(extracted_elements)

[[13  8]
 [16 17]]


In [6]:
# 3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].
array_integers = np.array([10, 20, 30, 40, 50, 60, 70, 80])
fancy_indexed_elements = array_integers[[1, 3, 4, 6]]
print(fancy_indexed_elements)

[20 40 50 70]


In [7]:
# 4. Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].
array_2D_example = np.random.randint(1, 20, (4, 5))
fancy_indexed_subarray = array_2D_example[[0, 2, 2], :][:, [1, 3]]
print(fancy_indexed_subarray)

[[10  5]
 [ 5  6]
 [ 5  6]]


In [8]:
# 5. From a 1D array of random integers, extract all elements that are greater than 8.
random_integers = np.random.randint(1, 15, 10)
greater_than_8 = random_integers[random_integers > 8]
print(greater_than_8)

[12 11 10]


In [9]:
# 6. Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.
array_2D_replace = np.random.randint(1, 20, (6, 6))
array_2D_replace[array_2D_replace > 13] = 0
print(array_2D_replace)

[[ 3 10 12  0  0 13]
 [ 5 12  6 10  0  0]
 [ 0  6  9  0  8  5]
 [ 6  0  0  1  0  0]
 [ 6  0  7  0  0 11]
 [ 0  3  0 12  0  1]]


**Broadcasting**

In [10]:
# 7. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).
array_1D = np.array([1, 2, 3])
array_2D_to_add = np.random.randint(1, 10, (4, 3))
broadcasted_addition = array_2D_to_add + array_1D
print(broadcasted_addition)

[[ 7  3  5]
 [ 3  8 11]
 [ 8 10  7]
 [ 6  3  6]]


In [11]:
# 8. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).
array_2D_to_multiply = np.random.randint(1, 10, (3, 3))
array_1D_multiply = np.array([2, 3, 4])
broadcasted_multiplication = array_2D_to_multiply * array_1D_multiply
print(broadcasted_multiplication)

[[ 8 24 36]
 [ 2  6 20]
 [ 4 24 36]]


In [12]:
# 9. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.
array_2D_shape_3_1 = np.random.randint(1, 10, (3, 1))
array_2D_shape_1_4 = np.random.randint(1, 10, (1, 4))
elementwise_addition = array_2D_shape_3_1 + array_2D_shape_1_4
print(elementwise_addition)

[[10  8 13 10]
 [ 5  3  8  5]
 [ 4  2  7  4]]


In [13]:
# 10. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.
array_3D_broadcast = np.random.randint(1, 10, (2, 3, 4))
array_2D_broadcast = np.random.randint(1, 10, (3, 4))
broadcasted_3d_addition = array_3D_broadcast + array_2D_broadcast
print(broadcasted_3d_addition)

[[[13  7  8  9]
  [15  7  5 12]
  [11  7  6 15]]

 [[12  2  4 10]
  [12  3  5 13]
  [11  4  2  8]]]


**Some More**

In [14]:
# 11. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.
array_2D_more = np.random.randint(1, 10, (6, 6))
sliced_array = array_2D_more[::2, ::2]
array_1d_more = np.array([1, 2, 3])
sliced_and_added = sliced_array + array_1d_more
print(sliced_and_added)

[[ 5 10  9]
 [ 8  4  9]
 [ 7  6 11]]


In [16]:
# 12. From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.
array_3D_more = np.random.randint(1, 10, (3, 2, 1))
sub_array = array_3D_more[:, :, 0]
array_2D_subtract = np.array([[1], [2]])
broadcasted_subtraction_corrected = sub_array - array_2D_subtract.T
print(broadcasted_subtraction_corrected)

[[ 5  5]
 [ 1 -1]
 [ 5 -1]]


In [15]:
# 13. Given a 2D array, extract the diagonal elements and create a 1D array.
array_2D_diag = np.random.randint(1, 10, (5, 5))
diagonal_elements = np.diag(array_2D_diag)
print(diagonal_elements)

[6 6 9 3 1]


In [19]:
# 14. Use slicing to reverse the order of elements in each row of a 2D array.
array_2D_reverse = np.random.randint(1, 10, (4, 5))
reversed_rows = array_2D_reverse[:, ::-1]
print(reversed_rows)

[[3 3 2 3 7]
 [3 7 9 1 7]
 [8 9 9 6 6]
 [1 9 9 4 8]]


In [16]:
# 15. Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.
array_3D_large = np.random.randint(1, 10, (7, 6, 5))
sub_array_large = array_3D_large[1:3, 2:5, 1:5]
array_1D_large = np.array([1, 2, 3, 4])
broadcasted_large_addition = sub_array_large + array_1D_large
print(broadcasted_large_addition)

[[[10  3 10  5]
  [ 6  3  5  5]
  [ 7 11  5  6]]

 [[ 7  9  5 10]
  [ 3  3 11 12]
  [10  5  7 13]]]


In [17]:

# 16. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.
array_2D_set_column = np.random.randint(1, 10, (4, 5))
array_2D_set_column[:, -1] = array_2D_set_column[:, 0] + array_2D_set_column[:, 1]
print(array_2D_set_column)

[[ 4  1  4  3  5]
 [ 8  2  3  9 10]
 [ 6  7  1  1 13]
 [ 4  2  4  5  6]]
