# **TASK_21**

In [1]:
import numpy as np

# **Linear Algebra Tasks**

# **1. Matrix Creation and Manipulation**

In [11]:
#Create various types of matrices (zero matrix, identity matrix, random matrix)
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

random_matrix = np.random.rand(3, 3)
print("\nRandom Matrix:\n", random_matrix)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix:
 [[0.87657118 0.72615223 0.1410353 ]
 [0.52401201 0.14894102 0.08292796]
 [0.70002377 0.84279997 0.97042104]]


In [13]:
#Perform basic matrix operations (addition, subtraction, multiplication)
addition= zero_matrix + identity_matrix
print("\nAddition:\n", addition)

subtraction = zero_matrix - identity_matrix
print("\nSubtraction:\n", subtraction)

multiplication = random_matrix * identity_matrix
print("\nMultiplication:\n", multiplication)



Addition:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Subtraction:
 [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]

Multiplication:
 [[0.87657118 0.         0.        ]
 [0.         0.14894102 0.        ]
 [0.         0.         0.97042104]]


In [14]:
#Transpose a matrix and find the determinant and inverse of a matrix.
transpose_matrix = np.transpose(random_matrix)
print("\nTranspose of Random Matrix:\n", transpose_matrix)

# Determinant of a matrix
determinant = np.linalg.det(random_matrix)
print("\nDeterminant of Random Matrix:\n", determinant)

# Inverse of a matrix
inverse_matrix = np.linalg.inv(random_matrix)
print("\nInverse of Random Matrix:\n", inverse_matrix)


Transpose of Random Matrix:
 [[0.87657118 0.52401201 0.70002377]
 [0.72615223 0.14894102 0.84279997]
 [0.1410353  0.08292796 0.97042104]]

Determinant of Random Matrix:
 -0.21409065451349255

Inverse of Random Matrix:
 [[-0.34865519  2.7362654  -0.18315783]
 [ 2.10406539 -3.51213393 -0.00566085]
 [-1.57585137  1.07641479  1.16751981]]


# **2. Solving Linear Equations**

In [15]:
# System of linear equations
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# Solve the system of equations Ax = b
x = np.linalg.solve(A, b)
print("Solution of the system of equations:\n", x)

# LU decomposition
from scipy.linalg import lu

P, L, U = lu(A)
print("\nLU Decomposition:\nP:\n", P, "\nL:\n", L, "\nU:\n", U)

# QR decomposition
Q, R = np.linalg.qr(A)
print("\nQR Decomposition:\nQ:\n", Q, "\nR:\n", R)


Solution of the system of equations:
 [2. 3.]

LU Decomposition:
P:
 [[1. 0.]
 [0. 1.]] 
L:
 [[1.         0.        ]
 [0.33333333 1.        ]] 
U:
 [[3.         1.        ]
 [0.         1.66666667]]

QR Decomposition:
Q:
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]] 
R:
 [[-3.16227766 -1.58113883]
 [ 0.          1.58113883]]


# **3. Eigenvalues and Eigenvectors**

In [16]:
# Matrix for eigenvalue and eigenvector calculation
matrix = np.array([[4, -2], [1, 1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Reconstructing the original matrix
reconstructed_matrix = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
print("\nReconstructed Matrix:\n", reconstructed_matrix)


Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

Reconstructed Matrix:
 [[ 4. -2.]
 [ 1.  1.]]


# **4. Vector Operations**

In [17]:
# Define two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Vector addition
vector_addition = vector_a + vector_b
print("Vector Addition:\n", vector_addition)

# Dot product
dot_product = np.dot(vector_a, vector_b)
print("\nDot Product:\n", dot_product)

# Cross product
cross_product = np.cross(vector_a, vector_b)
print("\nCross Product:\n", cross_product)

# Normalize a vector
norm_a = np.linalg.norm(vector_a)
normalized_vector = vector_a / norm_a
print("\nNormalized Vector:\n", normalized_vector)

# Compute vector norms
l2_norm = np.linalg.norm(vector_a)
print("\nL2 Norm of Vector A:\n", l2_norm)


Vector Addition:
 [5 7 9]

Dot Product:
 32

Cross Product:
 [-3  6 -3]

Normalized Vector:
 [0.26726124 0.53452248 0.80178373]

L2 Norm of Vector A:
 3.7416573867739413


# **5. Matrix Decomposition**

In [19]:
# PCA using SVD
from sklearn.decomposition import PCA
import seaborn as sns

# Loadind the Iris dataset
iris = sns.load_dataset("iris")
X = iris.drop(columns=['species'])

# Perform PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("PCA Result:\n", X_pca[:5])

# PCA using SVD
U, S, VT = np.linalg.svd(X - X.mean(axis=0), full_matrices=False)
X_svd = np.dot(U, np.diag(S))[:, :2]
print("\nSVD Result:\n", X_svd[:5])


PCA Result:
 [[-2.68412563  0.31939725]
 [-2.71414169 -0.17700123]
 [-2.88899057 -0.14494943]
 [-2.74534286 -0.31829898]
 [-2.72871654  0.32675451]]

SVD Result:
 [[-2.68412563 -0.31939725]
 [-2.71414169  0.17700123]
 [-2.88899057  0.14494943]
 [-2.74534286  0.31829898]
 [-2.72871654 -0.32675451]]


# **Calcalus Tasks**

# **1. Numerical Differentiation**

In [20]:
import numpy as np

# Define the function
def f(x):
    return x**2 + 3*x + 2

# Numerical derivative using forward difference
def forward_difference(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h

# Numerical derivative using backward difference
def backward_difference(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

# Numerical derivative using central difference
def central_difference(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

# Calculate derivatives at x = 1
x = 1
forward_diff = forward_difference(f, x)
backward_diff = backward_difference(f, x)
central_diff = central_difference(f, x)

print("Forward Difference at x=1:", forward_diff)
print("Backward Difference at x=1:", backward_diff)
print("Central Difference at x=1:", central_diff)


Forward Difference at x=1: 5.0000099999891745
Backward Difference at x=1: 4.99998999998752
Central Difference at x=1: 4.999999999988347


# **2. Numerical Integration**

In [21]:
from scipy.integrate import quad, simps

# Define the function
def f(x):
    return x**2 + 3*x + 2

# Numerical integration using quad (adaptive quadrature)
integral_quad, _ = quad(f, 0, 1)
print("Integral using quad:", integral_quad)

# Numerical integration using trapezoidal rule
x = np.linspace(0, 1, 100)
y = f(x)
integral_trapz = np.trapz(y, x)
print("Integral using trapezoidal rule:", integral_trapz)

# Numerical integration using Simpson's rule
integral_simps = simps(y, x)
print("Integral using Simpson's rule:", integral_simps)


Integral using quad: 3.833333333333333
Integral using trapezoidal rule: 3.833350338400843
Integral using Simpson's rule: 3.8333333333333335


# **3. Partial Derivatives**

In [22]:
# Define the multivariable function
def f(x, y):
    return x**2 + y**2 + x*y

# Partial derivative with respect to x
def partial_derivative_x(f, x, y, h=1e-5):
    return (f(x + h, y) - f(x, y)) / h

# Partial derivative with respect to y
def partial_derivative_y(f, x, y, h=1e-5):
    return (f(x, y + h) - f(x, y)) / h

# Calculate partial derivatives at (x, y) = (1, 1)
partial_x = partial_derivative_x(f, 1, 1)
partial_y = partial_derivative_y(f, 1, 1)

print("Partial derivative with respect to x at (1, 1):", partial_x)
print("Partial derivative with respect to y at (1, 1):", partial_y)


Partial derivative with respect to x at (1, 1): 3.0000100000204806
Partial derivative with respect to y at (1, 1): 3.0000100000204806
