In [3]:
import numpy as np

In [5]:
# Create a 1D NumPy array containing the integers from 0 to 9.
array_1D=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_1D)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# 2D NumPy array (3x3) containing random integers between 1 and 20.
array_2D=np.random.randint(1,20,(3,3))
print(array_2D)

[[15  9  4]
 [ 4  9 16]
 [16  6 14]]


In [7]:
# 3D NumPy array with dimensions (2, 3, 4) filled with ones.
array_3D=np.ones((2,3,4))
print(array_3D)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [8]:
# Element-wise addition of two 1D arrays
array_1=np.array([1, 2, 3, 4, 5])
array_2=np.array([6, 7, 8, 9, 10])
print(array_1+array_2)

[ 7  9 11 13 15]


In [10]:
# Element-wise multiplication of two 2D arrays.
array_3=np.array([[1, 2], [3, 4]])
array_4=np.array([[5, 6], [7, 8]])
print(array_3*array_4)

[[ 5 12]
 [21 32]]


In [12]:
# Dot product of two matrices.
matrix_1=np.array([[1, 2], [3, 4]])
matrix_2=np.array([[5, 6], [7, 8]])
print(np.dot(matrix_1,matrix_2))

[[19 22]
 [43 50]]


In [15]:
# Mean, median, and standard deviation of a 1D array
array_5=np.array([1, 2, 3, 4, 5])
print(np.mean(array_5))
print(np.median(array_5))
print(np.std(array_5))


3.0
3.0
1.4142135623730951


In [16]:
# Maximum and minimum values in a 2D array.
array_6=np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(array_6))
print(np.min(array_6))

6
1


In [18]:
# Array of 1000 random numbers from a normal distribution with mean 0 and standard deviation 1.
array_7=np.random.normal(0,1,1000)
print(array_7)

[-1.61362259e-01 -1.63412027e+00 -1.35218303e+00  1.41127553e+00
 -3.10234983e-01  1.39928390e-01  1.19355980e-01 -5.11951399e-01
 -4.40845778e-01 -2.49958290e-01  7.81048249e-01  6.41730031e-01
  8.60525867e-01 -7.11332261e-02 -1.61507508e+00  6.25801027e-02
  5.20211729e-01 -3.48830229e-01 -5.65713111e-01 -1.08572516e-01
 -1.37957632e-01  2.22789077e-01 -9.61358534e-02 -7.66314490e-01
 -1.20798081e+00 -1.18197960e+00 -1.21587504e-01 -1.11490297e+00
  7.06305039e-01  3.73979959e-01  3.27081198e-01  6.90620018e-01
 -1.18473341e+00  4.76551996e-01 -9.98136378e-01  1.63500546e-01
  1.08354103e+00  1.36474892e+00 -5.49546478e-01 -1.35980365e+00
 -3.44982694e-01  2.47256272e-01  1.40296950e+00 -5.12034211e-01
 -1.24849438e+00  6.95667159e-01 -1.29992145e+00  1.31393297e-01
 -6.18814229e-01  1.72349298e-02  1.10835823e+00 -1.07254804e+00
  2.44748378e-01 -1.42415282e+00  1.21757747e-02 -8.14562765e-01
  8.23498192e-01  1.16397445e+00  2.40892990e+00  2.82612839e-01
  3.50380271e+00  8.17793

In [19]:
# 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.
array_8=np.random.uniform(10,50,(5,5))
print(array_8)

[[23.55510769 15.87016642 31.25485889 20.8710163  14.44431848]
 [11.28045641 25.77827389 24.29227843 36.32711893 27.0296868 ]
 [36.34717264 18.06227467 31.14281088 45.14223517 34.72779511]
 [42.71286983 32.80493516 25.66799284 24.73236343 21.12364188]
 [17.78180362 12.69294364 27.26884597 36.64509956 38.52959173]]


In [21]:
# Cumulative sum of a 1D array.
array_9=np.array([1, 2, 3, 4, 5])
print(np.cumsum(array_9))

[ 1  3  6 10 15]


In [22]:
# Correlation coefficient matrix of a 2D array.
array_10=np.array([[1, 2, 3], [4, 5, 6]])
print(np.corrcoef(array_10))


[[1. 1.]
 [1. 1.]]


In [23]:
# Frequency of each outcome from simulating rolling a six-sided die 1000 times.
die_rolls=np.random.randint(1,7,1000)
print(np.bincount(die_rolls))

[  0 174 159 155 166 164 182]
